config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: "about"

  resources :books, only: [:index,:create,:show,:edit,:update,:destroy] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments, only:[:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :book_comments

  validates :title, presence: true
  validates :body, presence: true, length: {in: 1..200}
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  
  attachment :profile_image

  validates :name, presence: true,uniqueness: true,length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])

  end



end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    book_comment = BookComment.new(book_comment_params)
    book_comment.user_id = current_user.id
    book_comment.book_id = book.id
    book_comment.save
    redirect_back(fallback_location: root_path)

  end
  
  def destroy
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all.order(id: "DESC")
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(id: "DESC")
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <% if @book.errors.any? %>
  <h3 class="text-danger"><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
    <li class="text-danger"><%= message %></li>
  <% end %>
<% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Editing Book</h2>
    <%= form_with model: @book, local: true do |f| %>
      <div class="field mb-3 form-group">
        <%= f.label :title %></br>
        <%= f.text_field :title,autofocus: true, class: "form-control" %>
      </div>

      <div class="field mb-3 form-group">
        <%= f.label :body %><br>
        <%= f.text_area :body,autofocus: true, class: "form-control"%>
      </div>
        <%= f.submit 'Update Book',class: "btn btn-sm btn-success mb-3" %>
      <% end %>
      <%= link_to 'Show',book_path(@book) %>
      |
      <%= link_to 'Back',books_path %>
      </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <h3 class="text-danger"><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
    <li class="text-danger"><%= message %></li>
  <% end %>
<% end %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 63, 63, fallback: "no_image.jpg",size: "63x63" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</t>
            <td><%= current_user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= current_user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="row mb-3">
        <%= link_to '' , edit_user_path(current_user) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <%= render 'templates/post_book',new_book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th></th>
           <th></th>
         </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "40x40" %>
                <% end %>
              </td>
              <td><%= link_to book.title,book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
               <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                  <span class="text-danger"><i class="fa fa-heart" aria-hidden="true"></i><%= book.favorites.count %></span>
                  <% end %>
                <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                   <span class="text-primary"><i class="fa fa-heart" aria-hidden="true"></i><%= book.favorites.count %></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @book.user, :profile_image, :fill, 63, 63, fallback: "no_image.jpg",size: "63x63" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</t>
            <td><%= @book.user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= @book.user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="row mb-3">
        <%= link_to '' , edit_user_path(@book.user) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
     <%= render 'templates/post_book',new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "40x40" %></br >
                <%= @book.user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title,book_path(@book) %></td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                  <span class="text-danger"><i class="fa fa-heart" aria-hidden="true"></i><%= @book.favorites.count %></span>
                  <% end %>
                <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                   <span class="text-primary"><i class="fa fa-heart" aria-hidden="true"></i><%= @book.favorites.count %></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                コメント数：<%= @book.book_comments.count %>
              </td>
              <% if current_user == @book.user %>
              <td><%= link_to 'Edit',edit_book_path(@book),class: "btn btn-success btn-sm" %></td>
              <td><%= link_to 'Destroy',book_path(@book),class: "btn btn-danger btn-sm", method: :delete,data: {confirm: "本当に削除？"} %></td>
              <% end %>
            </tr>
            </tr>
        </tbody>
      </table>
      <% @book.book_comments.each do |comment| %>
      <div class="d-flex align-items-center">
        <div class="">
          <%= link_to user_path(comment.user) do %>
            <%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "40x40" %></br>
            <%= comment.user.name %>
          <% end %>
        </div>
        <div class="">
          <%= comment.comment %>
        </div>
        <div class="">
        <% if comment.user == current_user %>
          <%= link_to 'Destroy',book_book_comment_path(@book,comment),class: "btn btn-danger btn-sm",method: :delete %>
        <% end %>
        </div>
      </div>
      <% end %>

      <%= form_with model: [@book,@book_comment],url: book_book_comments_path(@book), local: true do |f| %>
        <div class="field mb-2">
          <%= f.text_area :comment, autofocus: true, class: "form-control" %>
        </div>
        <%= f.submit'送信'%>
      <% end %>
    </div>
  </div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="mb-3 mt-3">
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers!!</strong>
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="mb-3 mt-3">
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers!!</strong>
      </h1>
      <p class="mb-3">
        In
        <i class="fas fa-book"></i>
        <strong>Bookers,</strong>
      </p>
      <p class="mb-3">you can share and exchange your opinions , inpressions , and emotions</p>
      <p class="mb-3">about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up',new_user_registration_path,class: "btn btn-success btn-sm btn-block mb-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="shadow-sm bg-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to 'Bookers',root_path,class: "navbar-brand p-3 text-white" %>
          <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>

            <li class="nav-item p-2">
              <%= link_to ' Home',user_path(current_user), class: "fas fa-home nav-link text-white",'area-hidden' => true %>
            </li>

            <li class="nav-item p-2">
              <%= link_to ' Users',users_path, class: "fas fa-users nav-link text-white",'area-hidden' => true %>
            </li>

            <li class="nav-item p-2">
              <%= link_to ' Books',books_path, class: "fas fa-book-open nav-link text-white",'area-hidden' => true %>
            </li>

            <li class="nav-item p-2">
              <%= link_to 'Logout',destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-white",'area-hidden' => true, method: :delete %>
            </li>

            <% else %>

            <li class="nav-item p-2">
              <%= link_to ' Home',root_path, class: "fas fa-home nav-link text-white",'area-hidden' => true %>
            </li>

            <li class="nav-item p-2">
              <%= link_to ' About',about_path, class: "fas fa-link nav-link text-white",'area-hidden' => true %>
            </li>

            <li class="nav-item p-2">
              <%= link_to 'sign up',new_user_registration_path, class: "fas fa-user-plus nav-link text-white",'area-hidden' => true %>
            </li>

            <li class="nav-item p-2">
              <%= link_to 'Login',user_session_path, class: "fas fa-sign-in-alt nav-link text-white",'area-hidden' => true %>
            </li>

            <% end %>
          </ul>
        </div>
      </nav>
    </header>
      <p class="mb-3 text-success"><%= flash[:notice] %></p>
      <%= yield %>
      <footer>
        <div class="container mt-5">
          <div class="row">
            <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>
  </body>
</html>

app/views/templates/_post_book.html.erb
<h2>New book</h2>
<%= form_with model: new_book,url: books_path , local: true do |f| %>
  <div class="field mb-2">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>
  <div class="field mb-2">
    <%= f.label :body %><br />
    <%= f.text_area :body, autofocus: true, class: "form-control" %>
  </div>
  <%= f.submit'Create Book',class: "btn btn-success btn-sm" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
  <h3 class="text-danger"><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
  <% @user.errors.full_messages.each do |message| %>
    <li class="text-danger"><%= message %></li>
  <% end %>
<% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local: true do |f| %>
      <div class="field mb-3 form-group">
        <%= f.label :name %></br>
        <%= f.text_field :name,autofocus: true, class: "form-control" %>
      </div>

      <div class="field mb-3 form-group">
        <label for="inputImage">Image</label></br>
        <%= f.attachment_field :profile_image, placeholder: "選択されていません" %>
      </div>

      <div class="field mb-3 form-group">
        <%= f.label :introduction %><br>
        <%= f.text_area :introduction,autofocus: true, class: "form-control"%>
      </div>
        <%= f.submit 'Update User',class: "btn btn-sm btn-secondary" %>
      <% end %>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 63, 63, fallback: "no_image.jpg",size: "63x63" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</t>
            <td><%= current_user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= current_user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="row mb-3">
        <%= link_to '' , edit_user_path(current_user) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <%= render 'templates/post_book',new_book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
         <tr>
           <th>image</th>
           <th>name</th>
           <th></th>
         </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "40x40" %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 63, 63, fallback: "no_image.jpg",size: "63x63" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</t>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="row mb-3">
        <%= link_to '' , edit_user_path(@user) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <%= render 'templates/post_book',new_book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table  table-hover table-inverse">
        <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
         </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do%>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: "40x40" %>
                <% end %>
                </td>
              <td><%= link_to book.title,book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                  <span class="text-danger"><i class="fa fa-heart" aria-hidden="true"></i><%= book.favorites.count %></span>
                  <% end %>
                <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                   <span class="text-primary"><i class="fa fa-heart" aria-hidden="true"></i><%= book.favorites.count %></span>
                  <% end %>
                <% end %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>